//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч графика.
    /// </summary>
    // *** Start programmer edit section *** (ТЧГрафика CustomAttributes)

    // *** End programmer edit section *** (ТЧГрафика CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч графика")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧГрафикаE", new string[] {
            "ДатаПроведения as \'Дата проведения\'",
            "Время as \'Время\'",
            "МестоПроведения as \'Место проведения\'",
            "ГруппыВозраст as \'Группы возраст\'",
            "ГруппыВозраст.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "ГруппыВозраст.Наименование"})]
    [MasterViewDefineAttribute("ТЧГрафикаE", "ГруппыВозраст", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class ТЧГрафика : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаПроведения;
        
        private string fВремя;
        
        private string fМестоПроведения;
        
        private IIS.Prilozhenie.ГруппыВозраст fГруппыВозраст;
        
        private IIS.Prilozhenie.ГрафикМатчей fГрафикМатчей;
        
        // *** Start programmer edit section *** (ТЧГрафика CustomMembers)

        // *** End programmer edit section *** (ТЧГрафика CustomMembers)

        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (ТЧГрафика.Время CustomAttributes)

        // *** End programmer edit section *** (ТЧГрафика.Время CustomAttributes)
        [StrLen(255)]
        public virtual string Время
        {
            get
            {
                // *** Start programmer edit section *** (ТЧГрафика.Время Get start)

                // *** End programmer edit section *** (ТЧГрафика.Время Get start)
                string result = this.fВремя;
                // *** Start programmer edit section *** (ТЧГрафика.Время Get end)

                // *** End programmer edit section *** (ТЧГрафика.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧГрафика.Время Set start)

                // *** End programmer edit section *** (ТЧГрафика.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (ТЧГрафика.Время Set end)

                // *** End programmer edit section *** (ТЧГрафика.Время Set end)
            }
        }
        
        /// <summary>
        /// ДатаПроведения.
        /// </summary>
        // *** Start programmer edit section *** (ТЧГрафика.ДатаПроведения CustomAttributes)

        // *** End programmer edit section *** (ТЧГрафика.ДатаПроведения CustomAttributes)
        public virtual System.DateTime ДатаПроведения
        {
            get
            {
                // *** Start programmer edit section *** (ТЧГрафика.ДатаПроведения Get start)

                // *** End programmer edit section *** (ТЧГрафика.ДатаПроведения Get start)
                System.DateTime result = this.fДатаПроведения;
                // *** Start programmer edit section *** (ТЧГрафика.ДатаПроведения Get end)

                // *** End programmer edit section *** (ТЧГрафика.ДатаПроведения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧГрафика.ДатаПроведения Set start)

                // *** End programmer edit section *** (ТЧГрафика.ДатаПроведения Set start)
                this.fДатаПроведения = value;
                // *** Start programmer edit section *** (ТЧГрафика.ДатаПроведения Set end)

                // *** End programmer edit section *** (ТЧГрафика.ДатаПроведения Set end)
            }
        }
        
        /// <summary>
        /// МестоПроведения.
        /// </summary>
        // *** Start programmer edit section *** (ТЧГрафика.МестоПроведения CustomAttributes)

        // *** End programmer edit section *** (ТЧГрафика.МестоПроведения CustomAttributes)
        [StrLen(255)]
        public virtual string МестоПроведения
        {
            get
            {
                // *** Start programmer edit section *** (ТЧГрафика.МестоПроведения Get start)

                // *** End programmer edit section *** (ТЧГрафика.МестоПроведения Get start)
                string result = this.fМестоПроведения;
                // *** Start programmer edit section *** (ТЧГрафика.МестоПроведения Get end)

                // *** End programmer edit section *** (ТЧГрафика.МестоПроведения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧГрафика.МестоПроведения Set start)

                // *** End programmer edit section *** (ТЧГрафика.МестоПроведения Set start)
                this.fМестоПроведения = value;
                // *** Start programmer edit section *** (ТЧГрафика.МестоПроведения Set end)

                // *** End programmer edit section *** (ТЧГрафика.МестоПроведения Set end)
            }
        }
        
        /// <summary>
        /// Т ч графика.
        /// </summary>
        // *** Start programmer edit section *** (ТЧГрафика.ГруппыВозраст CustomAttributes)

        // *** End programmer edit section *** (ТЧГрафика.ГруппыВозраст CustomAttributes)
        [PropertyStorage(new string[] {
                "ГруппыВозраст"})]
        [NotNull()]
        public virtual IIS.Prilozhenie.ГруппыВозраст ГруппыВозраст
        {
            get
            {
                // *** Start programmer edit section *** (ТЧГрафика.ГруппыВозраст Get start)

                // *** End programmer edit section *** (ТЧГрафика.ГруппыВозраст Get start)
                IIS.Prilozhenie.ГруппыВозраст result = this.fГруппыВозраст;
                // *** Start programmer edit section *** (ТЧГрафика.ГруппыВозраст Get end)

                // *** End programmer edit section *** (ТЧГрафика.ГруппыВозраст Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧГрафика.ГруппыВозраст Set start)

                // *** End programmer edit section *** (ТЧГрафика.ГруппыВозраст Set start)
                this.fГруппыВозраст = value;
                // *** Start programmer edit section *** (ТЧГрафика.ГруппыВозраст Set end)

                // *** End programmer edit section *** (ТЧГрафика.ГруппыВозраст Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Prilozhenie.ГрафикМатчей.
        /// </summary>
        // *** Start programmer edit section *** (ТЧГрафика.ГрафикМатчей CustomAttributes)

        // *** End programmer edit section *** (ТЧГрафика.ГрафикМатчей CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ГрафикМатчей"})]
        public virtual IIS.Prilozhenie.ГрафикМатчей ГрафикМатчей
        {
            get
            {
                // *** Start programmer edit section *** (ТЧГрафика.ГрафикМатчей Get start)

                // *** End programmer edit section *** (ТЧГрафика.ГрафикМатчей Get start)
                IIS.Prilozhenie.ГрафикМатчей result = this.fГрафикМатчей;
                // *** Start programmer edit section *** (ТЧГрафика.ГрафикМатчей Get end)

                // *** End programmer edit section *** (ТЧГрафика.ГрафикМатчей Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧГрафика.ГрафикМатчей Set start)

                // *** End programmer edit section *** (ТЧГрафика.ГрафикМатчей Set start)
                this.fГрафикМатчей = value;
                // *** Start programmer edit section *** (ТЧГрафика.ГрафикМатчей Set end)

                // *** End programmer edit section *** (ТЧГрафика.ГрафикМатчей Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧГрафикаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧГрафикаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧГрафикаE", typeof(IIS.Prilozhenie.ТЧГрафика));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧГрафика.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧГрафика CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧГрафика CustomAttributes)
    public class DetailArrayOfТЧГрафика : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Prilozhenie.DetailArrayOfТЧГрафика members)

        // *** End programmer edit section *** (IIS.Prilozhenie.DetailArrayOfТЧГрафика members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧГрафика by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧГрафика.
        /// </summary>
        public DetailArrayOfТЧГрафика(IIS.Prilozhenie.ГрафикМатчей fГрафикМатчей) : 
                base(typeof(ТЧГрафика), ((ICSSoft.STORMNET.DataObject)(fГрафикМатчей)))
        {
        }
        
        public IIS.Prilozhenie.ТЧГрафика this[int index]
        {
            get
            {
                return ((IIS.Prilozhenie.ТЧГрафика)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Prilozhenie.ТЧГрафика dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
