//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч состава спорт.
    /// </summary>
    // *** Start programmer edit section *** (ТЧСоставаСпорт CustomAttributes)

    // *** End programmer edit section *** (ТЧСоставаСпорт CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч состава спорт")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧСоставаСпортE", new string[] {
            "НомерСпортсмена as \'Номер спортсмена\'",
            "Спортсмены as \'Спортсмены\'",
            "Спортсмены.ФИО as \'ФИО\'",
            "Спортсмены.ДатаРождения as \'Дата рождения\'"}, Hidden=new string[] {
            "Спортсмены.ФИО"})]
    [MasterViewDefineAttribute("ТЧСоставаСпортE", "Спортсмены", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class ТЧСоставаСпорт : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерСпортсмена;
        
        private IIS.Prilozhenie.Спортсмены fСпортсмены;
        
        private IIS.Prilozhenie.СоставКоманды fСоставКоманды;
        
        // *** Start programmer edit section *** (ТЧСоставаСпорт CustomMembers)

        // *** End programmer edit section *** (ТЧСоставаСпорт CustomMembers)

        
        /// <summary>
        /// НомерСпортсмена.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСоставаСпорт.НомерСпортсмена CustomAttributes)

        // *** End programmer edit section *** (ТЧСоставаСпорт.НомерСпортсмена CustomAttributes)
        public virtual int НомерСпортсмена
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСоставаСпорт.НомерСпортсмена Get start)

                // *** End programmer edit section *** (ТЧСоставаСпорт.НомерСпортсмена Get start)
                int result = this.fНомерСпортсмена;
                // *** Start programmer edit section *** (ТЧСоставаСпорт.НомерСпортсмена Get end)

                // *** End programmer edit section *** (ТЧСоставаСпорт.НомерСпортсмена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСоставаСпорт.НомерСпортсмена Set start)

                // *** End programmer edit section *** (ТЧСоставаСпорт.НомерСпортсмена Set start)
                this.fНомерСпортсмена = value;
                // *** Start programmer edit section *** (ТЧСоставаСпорт.НомерСпортсмена Set end)

                // *** End programmer edit section *** (ТЧСоставаСпорт.НомерСпортсмена Set end)
            }
        }
        
        /// <summary>
        /// Т ч состава спорт.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСоставаСпорт.Спортсмены CustomAttributes)

        // *** End programmer edit section *** (ТЧСоставаСпорт.Спортсмены CustomAttributes)
        [PropertyStorage(new string[] {
                "Спортсмены"})]
        [NotNull()]
        public virtual IIS.Prilozhenie.Спортсмены Спортсмены
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСоставаСпорт.Спортсмены Get start)

                // *** End programmer edit section *** (ТЧСоставаСпорт.Спортсмены Get start)
                IIS.Prilozhenie.Спортсмены result = this.fСпортсмены;
                // *** Start programmer edit section *** (ТЧСоставаСпорт.Спортсмены Get end)

                // *** End programmer edit section *** (ТЧСоставаСпорт.Спортсмены Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСоставаСпорт.Спортсмены Set start)

                // *** End programmer edit section *** (ТЧСоставаСпорт.Спортсмены Set start)
                this.fСпортсмены = value;
                // *** Start programmer edit section *** (ТЧСоставаСпорт.Спортсмены Set end)

                // *** End programmer edit section *** (ТЧСоставаСпорт.Спортсмены Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Prilozhenie.СоставКоманды.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСоставаСпорт.СоставКоманды CustomAttributes)

        // *** End programmer edit section *** (ТЧСоставаСпорт.СоставКоманды CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "СоставКоманды"})]
        public virtual IIS.Prilozhenie.СоставКоманды СоставКоманды
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСоставаСпорт.СоставКоманды Get start)

                // *** End programmer edit section *** (ТЧСоставаСпорт.СоставКоманды Get start)
                IIS.Prilozhenie.СоставКоманды result = this.fСоставКоманды;
                // *** Start programmer edit section *** (ТЧСоставаСпорт.СоставКоманды Get end)

                // *** End programmer edit section *** (ТЧСоставаСпорт.СоставКоманды Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСоставаСпорт.СоставКоманды Set start)

                // *** End programmer edit section *** (ТЧСоставаСпорт.СоставКоманды Set start)
                this.fСоставКоманды = value;
                // *** Start programmer edit section *** (ТЧСоставаСпорт.СоставКоманды Set end)

                // *** End programmer edit section *** (ТЧСоставаСпорт.СоставКоманды Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧСоставаСпортE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧСоставаСпортE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧСоставаСпортE", typeof(IIS.Prilozhenie.ТЧСоставаСпорт));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧСоставаСпорт.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧСоставаСпорт CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧСоставаСпорт CustomAttributes)
    public class DetailArrayOfТЧСоставаСпорт : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Prilozhenie.DetailArrayOfТЧСоставаСпорт members)

        // *** End programmer edit section *** (IIS.Prilozhenie.DetailArrayOfТЧСоставаСпорт members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧСоставаСпорт by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧСоставаСпорт.
        /// </summary>
        public DetailArrayOfТЧСоставаСпорт(IIS.Prilozhenie.СоставКоманды fСоставКоманды) : 
                base(typeof(ТЧСоставаСпорт), ((ICSSoft.STORMNET.DataObject)(fСоставКоманды)))
        {
        }
        
        public IIS.Prilozhenie.ТЧСоставаСпорт this[int index]
        {
            get
            {
                return ((IIS.Prilozhenie.ТЧСоставаСпорт)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Prilozhenie.ТЧСоставаСпорт dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
